import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS, useAppFonts} from '../../constants/AppConst';
const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    height: '100%',
    width: '100%',
  },
  header: {
    paddingTop: 10,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute', 
    top: 0, 
    left: 0, 
    right: 0, 
    zIndex: 1000, 
  },
  sectionIndicators: {
    flex: 1,
  },
  sectionIndicatorsContent: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 2,
  },
  sectionIndicator: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    minWidth: 60,
  },
  sectionLabel: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: FONTS.regular,
  },
  sectionSlots: {
    color: 'white',
    fontSize: 10,
    marginTop: 2,
    fontFamily: FONTS.regular,
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 5,
  },
  connectionText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: FONTS.regular,
  },
  refreshButton: {
    position: 'absolute',
    top: 120,
    left: 20,
    backgroundColor: 'rgba(178, 32, 32, 0.8)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    zIndex: 2000,
    elevation: 10,
  },
  refreshText: {
    color: 'white',
    fontSize: 12,
    fontFamily: FONTS.semiBold,
  },
  mapContainer: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    paddingBottom: 100,
    marginTop: 100,
    marginRight: 300
  },
  mapFrame: {
    flex: 1,
    overflow: 'visible',
    paddingBottom: 0,
    marginLeft: -100
  },
  mapWrapper: {
    flex: 1,
  },
  arrow1: { position: 'absolute', right: 140, top: 170},
  arrow2: { position: 'absolute', right: 160, top: 120},
  arrow3: { position: 'absolute', right: 230, top: 120},
  arrow4: { position: 'absolute', right: 270, top: 160},
  arrow5: { position: 'absolute', right: 270, top: 260},
  arrow6: { position: 'absolute', right: 350, top: 285},
  arrow7: { position: 'absolute', right: 470, top: 285},
  arrow8: { position: 'absolute', right: 600, top: 285},
  arrow9: { position: 'absolute', right: 650, top: 390},
  arrow11: { position: 'absolute', right: 580, top: 470},
  arrow12: { position: 'absolute', right: 430, top: 470},
  arrow13: { position: 'absolute', right: 280, top: 470},
  arrow14: { position: 'absolute', right: 220, top: 510},
  arrow15: { position: 'absolute', right: 220, top: 620},
  arrow16: { position: 'absolute', right: 220, top: 750},
  arrow17: { position: 'absolute', right: 180, top: 840},
  arrow18: { position: 'absolute', right: 140, top: 750},
  arrow19: { position: 'absolute', right: 140, top: 620},
  arrow20: { position: 'absolute', right: 140, top: 490},
  arrow21: { position: 'absolute', right: 90, top: 410},
  parkingLayout: {
    width: 800,
    height: height + 200,
    backgroundColor: '#2C2C2C',
  },
  elevator1: {
    position: 'absolute',
    left: 450,
    top: 210,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 60,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator2: {
    position: 'absolute',
    left: 460,
    top: 525,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator3:{
    position: 'absolute',
    left: 657,
    top: 495,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{rotate: '90deg'}]
  },
   elevatorText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  stairs: {
    position: 'absolute',
    left: 30,
    top: 225,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 80,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '-90deg'}]
  },
  stairsText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  entrance: {
    position: 'absolute',
    right: 90,
    top: 260,
    backgroundColor: COLORS.primary,
    padding: 8,
    borderRadius: 4,
    width: 90,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  entranceText: {
    color: 'white',
    fontSize: 15,
    fontFamily: FONTS.semiBold,
    textAlign: 'center',
  },
  exitSign: {
    position: 'absolute',
    right: 120,
    top: 400,
    backgroundColor: 'transparent',
    padding: 8,
    borderRadius: 4,
    width: 100,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exitText: {
    color: 'white',
    fontSize: 24,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  bottomPanel: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 13,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  buildingName: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: FONTS.semiBold,
  },
  floorInfo: {
    marginBottom: 20,
  },
  floorDetails: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  floorLabel: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  floorNumber: {
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  availableLabel: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  availableNumber: {
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  lastUpdated: {
    marginTop: 10,
    alignItems: 'center',
  },
  lastUpdatedText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontFamily: FONTS.regular,
  },
  bottomButtons: {
    flexDirection: 'row',
    gap: 15,
    justifyContent: 'center',
    marginBottom: 10
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flex: 1,
    maxWidth: 150,
  },
  secondaryButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: FONTS.regular,
  },
  primaryButton: {
    backgroundColor: '#B22020',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flex: 1,
    maxWidth: 120,
  },
  primaryButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: FONTS.semiBold,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  clearRouteButton: {
    position: 'absolute',
    top: 120,
    right: 20,
    backgroundColor: 'rgba(255, 0, 0, 0.8)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    zIndex: 2000,
    elevation: 10,
  },
  clearRouteText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONTS.semiBold,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 15,
  },
  serviceIndicator: {
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderRadius: 8,
  },
  serviceText: {
    color: '#4CAF50',
    fontSize: 10,
    fontWeight: '600',
  },
  serviceStatsText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    marginTop: 2,
    fontFamily: FONTS.regular,
  },

});