import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTS, useAppFonts} from '../../constants/AppConst';
const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    height: '100%',
    width: '100%',
  },
  header: {
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: 'white',
    fontFamily: FONTS.semiBold,
  },
  sectionIndicators: {
    flex: 1,
  },
  sectionIndicatorsContent: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 2,
  },
  sectionIndicator: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    minWidth: 60,
  },
  sectionLabel: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: FONTS.regular,
  },
  sectionSlots: {
    color: 'white',
    fontSize: 10,
    marginTop: 2,
    fontFamily: FONTS.regular,
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 5,
  },
  connectionText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: FONTS.regular,
  },
  refreshButton: {
    position: 'absolute',
    top: 150,
    left: 20,
    backgroundColor: 'rgba(178, 32, 32, 0.8)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    zIndex: 2000,
    elevation: 10,
  },
  refreshText: {
    color: 'white',
    fontSize: 12,
    fontFamily: FONTS.semiBold,
  },
  mapContainer: {
    flex: 1,
    backgroundColor: '#2C2C2C',
    paddingBottom: 100,
    marginTop: 100,
    marginRight: 300
  },
  mapFrame: {
    flex: 1,
    overflow: 'visible',
    paddingBottom: 0,
    marginLeft: -100
  },
  mapWrapper: {
    flex: 1,
  },
  arrow1: { position: 'absolute', right: 140, top: 170},
  arrow2: { position: 'absolute', right: 160, top: 120},
  arrow3: { position: 'absolute', right: 230, top: 120},
  arrow4: { position: 'absolute', right: 270, top: 160},
  arrow5: { position: 'absolute', right: 270, top: 260},
  arrow6: { position: 'absolute', right: 350, top: 285},
  arrow7: { position: 'absolute', right: 470, top: 285},
  arrow8: { position: 'absolute', right: 600, top: 285},
  arrow9: { position: 'absolute', right: 650, top: 390},
  arrow11: { position: 'absolute', right: 580, top: 470},
  arrow12: { position: 'absolute', right: 430, top: 470},
  arrow13: { position: 'absolute', right: 280, top: 470},
  arrow14: { position: 'absolute', right: 220, top: 510},
  arrow15: { position: 'absolute', right: 220, top: 620},
  arrow16: { position: 'absolute', right: 220, top: 750},
  arrow17: { position: 'absolute', right: 180, top: 840},
  arrow18: { position: 'absolute', right: 140, top: 750},
  arrow19: { position: 'absolute', right: 140, top: 620},
  arrow20: { position: 'absolute', right: 140, top: 490},
  arrow21: { position: 'absolute', right: 90, top: 410},
  parkingLayout: {
    width: 800,
    height: height + 200,
    backgroundColor: '#2C2C2C',
  },
  elevator1: {
    position: 'absolute',
    left: 450,
    top: 210,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 60,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator2: {
    position: 'absolute',
    left: 460,
    top: 525,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator3:{
    position: 'absolute',
    left: 657,
    top: 495,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{rotate: '90deg'}]
  },
   elevatorText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  stairs: {
    position: 'absolute',
    left: 30,
    top: 225,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 80,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '-90deg'}]
  },
  stairsText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  entrance: {
    position: 'absolute',
    right: 90,
    top: 260,
    backgroundColor: COLORS.green,
    padding: 8,
    borderRadius: 4,
    width: 90,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  entranceText: {
    color: 'white',
    fontSize: 15,
    fontFamily: FONTS.semiBold,
    textAlign: 'center',
  },
  exitSign: {
    position: 'absolute',
    right: 120,
    top: 400,
    backgroundColor: 'transparent',
    padding: 8,
    borderRadius: 4,
    width: 100,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exitText: {
    color: 'white',
    fontSize: 24,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  bottomPanel: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 13,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  buildingName: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: FONTS.semiBold,
  },
  floorInfo: {
    marginBottom: 20,
  },
  floorDetails: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  floorLabel: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  floorNumber: {
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  availableLabel: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  availableNumber: {
    color: 'white',
    fontSize: 32,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  lastUpdated: {
    marginTop: 10,
    alignItems: 'center',
  },
  lastUpdatedText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontFamily: FONTS.regular,
  },
  bottomButtons: {
    flexDirection: 'row',
    gap: 15,
    justifyContent: 'center',
    marginBottom: 10
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    flex: 1,
    maxWidth: 150,
  },
  secondaryButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: FONTS.regular,
  },
  primaryButton: {
    backgroundColor: '#B22020',
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: 25,
    flex: 1,
    maxWidth: 140,
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: FONTS.semiBold,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  clearRouteButton: {
    position: 'absolute',
    top: 150,
    right: 20,
    backgroundColor: 'rgba(255, 0, 0, 0.8)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    zIndex: 2000,
    elevation: 10,
  },
  clearRouteText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONTS.semiBold,
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 15,
  },
  serviceIndicator: {
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderRadius: 8,
  },
  serviceText: {
    color: '#4CAF50',
    fontSize: 10,
    fontWeight: '600',
  },
  serviceStatsText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    marginTop: 2,
    fontFamily: FONTS.regular,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 25,
  },
  navigationModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    width: '100%',
    maxWidth: 500,
    overflow: 'hidden',
  },
  navigationModalHeader: {
    backgroundColor: '#c62828',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  navigationIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  navigationHeaderText: {
    flex: 1,
  },
  navigationModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
    fontFamily: FONTS.semiBold,
  },
  navigationModalSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: FONTS.regular,
  },
  navigationCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigationModalContent: {
    padding: 24,
  },
  navigationQuestion: {
    fontSize: 13,
    color: '#333',
    lineHeight: 24,
    fontFamily: FONTS.regular,
  },
  navigationModalActions: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
  },
  navigationCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
  },
  navigationCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    fontFamily: FONTS.semiBold,
  },
  navigationGuideButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#c62828',
    alignItems: 'center',
  },
  navigationGuideText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    fontFamily: FONTS.semiBold,
  },
  parkingConfirmOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  parkingConfirmContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
  },
  parkingConfirmIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.green,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  parkingConfirmTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: FONTS.semiBold,
    marginBottom: 12,
    textAlign: 'center',
  },
  parkingConfirmMessage: {
    fontSize: 12,
    color: '#666',
    fontFamily: FONTS.regular,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  parkingConfirmButtonsContainer: {
    width: '100%',
    gap: 12,
  },
  parkingConfirmYesButton: {
    backgroundColor: COLORS.green,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  parkingConfirmYesButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
    fontFamily: FONTS.semiBold,
  },
  parkingConfirmNoButton: {
    backgroundColor: '#F0F0F0',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  parkingConfirmNoButtonText: {
    color: '#666',
    fontWeight: '600',
    fontSize: 16,
    fontFamily: FONTS.semiBold,
  },
  floorModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  floorModalBackdrop: {
    flex: 1,
  },
  floorModalContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  floorModalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#DDD',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  floorModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  floorModalHeaderText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: FONTS.semiBold,
  },
  floorOptionsContainer: {
    gap: 12,
  },
  floorOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  floorOptionCurrent: {
    backgroundColor: COLORS.primary,
    borderWidth: 0,
  },
  floorOptionInactive: {
    backgroundColor: '#F8F9FA',
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  floorIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  floorIconCurrent: {
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  floorIconInactive: {
    backgroundColor: '#FFF',
  },
  floorIconText: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: FONTS.semiBold,
  },
  floorInfoContainer: {
    flex: 1,
  },
  floorLabel1: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: FONTS.semiBold,
    marginBottom: 2,
  },
  floorAvailability: {
    fontSize: 13,
    fontFamily: FONTS.regular,
  },
  floorStatusContainer: {
    alignItems: 'flex-end',
  },
  floorStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  floorStatusBadgeCurrent: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  floorStatusBadgeNoData: {
    backgroundColor: '#E0E0E0',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  floorStatusText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  floorStatusTextCurrent: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  floorStatusTextNoData: {
    color: '#888',
    fontSize: 12,
    fontWeight: '600',
  },
  floorModalCancelButton: {
    marginTop: 20,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: 12,
  },
  floorModalCancelText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
    fontFamily: FONTS.semiBold,
  },
  floorOptionDisabled: {
    opacity: 0.5,
    backgroundColor: '#E8E8E8',
  },
  floorIconDisabled: {
    backgroundColor: '#cfcece',
  },
<<<<<<< HEAD

  // Success Modal Styles
  successModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  successModalContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
  },
  successModalIconContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: COLORS.green,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  successModalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    fontFamily: FONTS.semiBold,
    marginBottom: 12,
    textAlign: 'center',
  },
  successModalMessage: {
<<<<<<< HEAD
    fontSize: 12,
=======
    fontSize: 15,
>>>>>>> rxtn
    color: '#666',
    fontFamily: FONTS.regular,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  successModalButton: {
    backgroundColor: COLORS.green,
    paddingVertical: 14,
    paddingHorizontal: 50,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
  },
  successModalButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
    fontFamily: FONTS.semiBold,
  },

  // Spot Taken Modal Styles
  spotTakenModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  spotTakenModalContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
  },
  spotTakenModalIconContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#FF9800',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  spotTakenModalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
<<<<<<< HEAD
    color: COLORS.primary,
=======
    color: '#333',
>>>>>>> rxtn
    fontFamily: FONTS.semiBold,
    marginBottom: 12,
    textAlign: 'center',
  },
  spotTakenModalMessage: {
    fontSize: 15,
    color: '#666',
    fontFamily: FONTS.regular,
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 22,
  },
  suggestedSpotsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
  },
  suggestedSpotBadge: {
    backgroundColor: COLORS.green,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 10,
  },
  suggestedSpotText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: FONTS.semiBold,
  },
  spotTakenHint: {
    fontSize: 13,
    color: '#888',
    fontFamily: FONTS.regular,
    textAlign: 'center',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  spotTakenModalButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 50,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
  },
  spotTakenModalButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
    fontFamily: FONTS.semiBold,
  },
=======
>>>>>>> parent of 861edc2 (added stop notif)
});