import { StyleSheet } from 'react-native';
import { FONTS } from '../../constants/AppConst';

export const mapLayoutStyles = StyleSheet.create({
  // Elevators
  elevator1: {
    position: 'absolute',
    left: 450,
    top: 210,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 60,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator2: {
    position: 'absolute',
    left: 460,
    top: 525,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  elevator3: {
    position: 'absolute',
    left: 657,
    top: 495,
    backgroundColor: '#d5d821ff',
    padding: 10,
    borderRadius: 4,
    width: 85,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '90deg' }],
  },
  elevatorText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  
  // Stairs
  stairs: {
    position: 'absolute',
    left: 30,
    top: 225,
    backgroundColor: '#d5d821ff',
    padding: 8,
    borderRadius: 4,
    width: 80,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '-90deg' }],
  },
  stairsText: {
    color: 'black',
    fontSize: 9,
    textAlign: 'center',
    fontFamily: FONTS.regular,
  },
  
  // Entrance
  entrance: {
    position: 'absolute',
    right: 90,
    top: 260,
    backgroundColor: '#3ed120ff',
    padding: 8,
    borderRadius: 4,
    width: 90,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  entranceText: {
    color: 'black',
    fontSize: 15,
    fontFamily: FONTS.semiBold,
    textAlign: 'center',
  },
  
  // Exit
  exitSign: {
    position: 'absolute',
    right: 120,
    top: 400,
    backgroundColor: 'transparent',
    padding: 8,
    borderRadius: 4,
    width: 100,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  exitText: {
    color: 'white',
    fontSize: 24,
    textAlign: 'center',
    fontFamily: FONTS.semiBold,
  },
  
  // Arrows
  arrow1: { position: 'absolute', right: 140, top: 170 },
  arrow2: { position: 'absolute', right: 160, top: 120 },
  arrow3: { position: 'absolute', right: 230, top: 120 },
  arrow4: { position: 'absolute', right: 270, top: 160 },
  arrow5: { position: 'absolute', right: 270, top: 260 },
  arrow6: { position: 'absolute', right: 350, top: 285 },
  arrow7: { position: 'absolute', right: 470, top: 285 },
  arrow8: { position: 'absolute', right: 600, top: 285 },
  arrow9: { position: 'absolute', right: 650, top: 390 },
  arrow11: { position: 'absolute', right: 580, top: 470 },
  arrow12: { position: 'absolute', right: 430, top: 470 },
  arrow13: { position: 'absolute', right: 280, top: 470 },
  arrow14: { position: 'absolute', right: 220, top: 510 },
  arrow15: { position: 'absolute', right: 220, top: 620 },
  arrow16: { position: 'absolute', right: 220, top: 750 },
  arrow17: { position: 'absolute', right: 180, top: 690 },
  arrow18: { position: 'absolute', right: 140, top: 750 },
  arrow19: { position: 'absolute', right: 140, top: 620 },
  arrow20: { position: 'absolute', right: 140, top: 490 },
  arrow21: { position: 'absolute', right: 90, top: 410 },
});