import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'flex-start',
    paddingTop: 100,
    paddingHorizontal: 20,
  },
  container: {
    backgroundColor: 'white',
    borderRadius: 16,
    maxHeight: '90%',
    minHeight: 450,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  headerLeft: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'Poppins_600SemiBold',
    color: '#333',
  },
  swipeHint: {
    fontSize: 10,
    fontFamily: 'Poppins_400Regular',
    color: '#999',
    marginTop: 2,
  },
  refreshButton: {
    padding: 8,
    borderRadius: 12,
  },
  refreshButtonLoading: {
    backgroundColor: '#f5f5f5',
  },
  filterContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  filterTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#f5f5f5',
    marginRight: 8,
  },
  activeFilterTab: {
    backgroundColor: '#B22020',
  },
  filterTabText: {
    fontSize: 12,
    fontFamily: 'Poppins_600SemiBold',
    color: '#666',
  },
  activeFilterTabText: {
    color: 'white',
  },
  notificationsList: {
    flex: 1,
    maxHeight: 300,
  },
  swipeContainer: {
    position: 'relative',
    backgroundColor: '#EF4444',
    overflow: 'hidden',
  },
  deleteButtonContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 120,
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  deleteButtonText: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Poppins_600SemiBold',
    marginTop: 4,
  },
  swipeableContent: {
    backgroundColor: 'white',
  },
  notificationItem: {
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  unreadNotification: {
    backgroundColor: '#fafafa',
    borderLeftWidth: 3,
    borderLeftColor: '#B22020',
  },
  deletingNotification: {
    opacity: 0.5,
  },
  notificationContent: {
    flex: 1,
  },
  notificationHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  iconContainer: {
    marginRight: 12,
    marginTop: 2,
  },
  notificationTextContainer: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: 14,
    fontFamily: 'Poppins_600SemiBold',
    color: '#333',
    marginBottom: 2,
  },
  notificationTime: {
    fontSize: 11,
    fontFamily: 'Poppins_400Regular',
    color: '#999',
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#B22020',
    marginTop: 4,
    marginRight: 8,
  },
  swipeIndicator: {
    marginLeft: 8,
    opacity: 0.3,
  },
  notificationMessage: {
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
    color: '#666',
    lineHeight: 16,
    marginLeft: 32,
  },
  unreadText: {
    color: '#333',
    fontFamily: 'Poppins_600SemiBold',
  },
  feedbackDetails: {
    marginLeft: 32,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  feedbackIdContainer: {
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  feedbackIdText: {
    fontSize: 10,
    fontFamily: 'Poppins_600SemiBold',
    color: '#B22020',
  },
  feedbackPreview: {
    fontSize: 11,
    fontFamily: 'Poppins_400Regular',
    color: '#666',
    fontStyle: 'italic',
    marginBottom: 4,
  },
  actionHint: {
    fontSize: 10,
    fontFamily: 'Poppins_400Regular',
    color: '#999',
    marginTop: 4,
  },
  parkingDetails: {
    marginLeft: 32,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  floorInfo: {
    fontSize: 11,
    fontFamily: 'Poppins_600SemiBold',
    color: '#48D666',
    marginBottom: 2,
  },
  spotsInfo: {
    fontSize: 11,
    fontFamily: 'Poppins_400Regular',
    color: '#666',
    marginBottom: 4,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateText: {
    fontSize: 14,
    fontFamily: 'Poppins_600SemiBold',
    color: '#999',
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  emptyStateSubtext: {
    fontSize: 12,
    fontFamily: 'Poppins_400Regular',
    color: '#ccc',
    textAlign: 'center',
    lineHeight: 16,
  },
  markAllReadButton: {
    backgroundColor: '#f8f9fa',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    alignItems: 'center',
  },
  markAllReadText: {
    fontSize: 14,
    fontFamily: 'Poppins_600SemiBold',
    color: '#B22020',
  },
  floorBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  specificSpotsContainer: {
    marginTop: 8,
    marginBottom: 4,
  },
  specificSpotsLabel: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
    marginBottom: 6,
  },
  spotIdsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  spotIdBadge: {
    backgroundColor: '#48D666',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 4,
    marginBottom: 4,
  },
  spotIdText: {
    fontSize: 11,
    color: 'white',
    fontWeight: '600',
  },
  spotsCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  floorUpdateDetails: {
    marginTop: 8,
    padding: 8,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#2196F3',
  },
  floorUpdateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  occupancyBadge: {
    backgroundColor: '#2196F3',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  occupancyText: {
    fontSize: 11,
    color: 'white',
    fontWeight: '600',
  },
  changeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  changeText: {
    fontSize: 11,
    fontWeight: '600',
    marginLeft: 4,
  },
});